- name: delete a snapshot of a flashblade volume
  hosts: flashblade
  gather_facts: no
  connection: local
  tasks:
    - include_csv: src=fbstorage.csv
    - name: delete a snapshot of a volume in flashblade
      purefb_snap:
        name: "{{ item.vol }}"
        suffix: zz-andyssnaps
        state:  absent
        fb_url: "{{ item.array }}"
        api_token: "{{ item.token }}"
      with_items: "{{ fbstorage }}"


