- name: add Flashblade Volumes
  hosts: flashblade
  gather_facts: no
  connection: local
  tasks:
    - include_csv: src=fbstorage.csv
    - name: add a volume
      purefb_fs:
        name: "{{ item.vol }}"
        size: "{{ item.storage }}"
        nfs: "{{ item.enfs }}"
        state: "{{ item.state }}"
        fb_url: "{{ item.array }}"
        api_token: "{{ item.token }}"
      with_items: "{{ fbstorage }}"

