- name: Manage protection groups on Pure Storage FlashArrays
  hosts: flasharray
  gather_facts: no
  connection: local
  tasks:
    - include_csv: src=storage.csv
    - name: Create new local protection group 
      purefa_pg:
        pgroup: "{{ item.pg }}"
        hostgroup: "{{ item.hostg }}"
        target: RedDotFB
        state: "{{ item.state }}"
        fa_url: "{{ item.array }}"
        api_token: "{{ item.token }}"
      with_items: "{{ storage }}"
