- name: Manage volume snapshots on Pure Storage FlashArrays 
  hosts: flasharray
  gather_facts: no
  connection: local
  tasks:
    - include_csv: src=storage.csv
    - name: Create snapshot
      purefa_snap:
        name: zz-apdev
        suffix: ansible
        state: "{{ item.state }}"
        fa_url: "{{ item.array }}"
        api_token: "{{ item.token }}"
      with_items: "{{ storage }}"
