- name: add volumes
  hosts: flasharray
  gather_facts: no
  connection: local
  tasks:
    - include_csv: src=storage.csv
    - name: add a volume
      purefa_volume:
        name: "{{ item.vol }}" 
        size: "{{ item.storage }}"
        state: "{{ item.state }}"
        fa_url: "{{ item.array }}"
        api_token: "{{ item.token }}"
      with_items: "{{ storage }}"
